version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT=root
      - MYSQL_PASSWORD_ROOT=root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - ${database}:80
